redis:
  image: "redis:3.0.7-alpine"

user:
  build: user
  ports:
    - "8080:8080"
  volumes:
    - "./user:/myapp"
  command: "go run say_hello.go"

user-redis:
  build: user-redis
  env_file: user-redis/.env
  ports:
    - "8080:8080"
  links:
    - "redis"
  volumes:
    - "./user-redis:/myapp"
  command: "go run user_register.go"
